### ISSUE TITLE
 Unable to resolve service for type 'Microsoft.AspNetCore.DataProtection.IDataProtectionProvider'

### ISSUE THREAD

**Issue by shaunluttin** [aspnet-contrib/AspNet.Security.OAuth.Extensions#31]
```
Unhandled Exception: System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.DataProtection.IDataProtectionProvider' while attempting to activate 'AspNet.Security.OAuth.Validation.OAuthValidationMiddleware'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)

   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass3_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Application.Program.Main(String[] args)
```

This is our configuration: 

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvcCore()
            .AddJsonFormatters();
}

public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
{
    loggerFactory.AddConsole(LogLevel.Debug);

    app.UseOAuthValidation(options =>
    {
        options.Audiences.Add("resource_server");
    });

    app.UseMvc();
}
```

**Comment by shaunluttin** [comment]
We needed to add this to our service configuration: 

    services.AddAuthentication();

**Comment by PinpointTownes** [comment]
I'll add a note in the README to make sure it's clear that you need the authentication services.
