### ISSUE TITLE
Some access tokens cause System.InvalidCastException. 

### ISSUE THREAD

**Issue by shaunluttin** [aspnet-contrib/AspNet.Security.OAuth.Extensions#32]
This request causes no error: 
```
GET http://localhost:5002/api/simple HTTP/1.1
Host: localhost:5002
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlExWkVESENZWVBLVUtPNl9aRzBfWTFBU09aTC05TldKLURYVVdKTkQiLCJ0eXAiOiJKV1QifQ.eyJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6IjllMDljYjU5LWRiNDAtNGUyZC1iZGNmLWJjYjZkOWVlYmYwZSIsImp0aSI6ImZhMGIwNDhmLWNjYTQtNGZiZi05NWQ4LWMwZjA0MjUzYmIxMiIsInVzYWdlIjoiYWNjZXNzX3Rva2VuIiwic3ViIjoiNjIzNTk3NTItM2I5YS00Y2VjLWFiYjQtZWVmMDU3NzdmNjQ4IiwibmJmIjoxNDYxODg2MTM3LCJleHAiOjE0NjE4ODk3MzcsImlhdCI6MTQ2MTg4NjEzNywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwLyJ9.Ie8sqJyEvR_vNpTgSfo_5CLKTQBQqKo2YO3hHlnGmAqwQeQJ76R6o-ss-iSqFtHW8eSWlfVxmlYqudCZ-AawRStaKuQ7sJY-nevTXehdMKBQXeD_h6CxZp2ZHeAqvUy3pcVqfuWIorBOHK3wFMNp5KSSzTMG0VzE_sK393lMGtlCtMEKr2m-FSo0lJ98i-Y9USMvFaaBHY5Ey4u6GG8Kk-YW5TXYAHtvcFSAbzBdVi_PerETDzo4pdsWDPpDsNo1wL-dG8UXBMR4SYCLpYy2fndgA9PzNteGfI8xqHwFcvazIm0UdwAQtdUlcepTajszMntOmeNnni5QYPSYJ-Dnsg


```
This request causes an error: 
```
GET http://localhost:5002/api/simple HTTP/1.1
Host: localhost:5002
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlExWkVESENZWVBLVUtPNl9aRzBfWTFBU09aTC05TldKLURYVVdKTkQiLCJ0eXAiOiJKV1QifQ.eyJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6Ijc5YTRmMWYyLTA5Y2YtNDU0MC04YjFiLTVlOGQxZjc1MTBlOSIsImp0aSI6IjdhMGJkMGFjLWE5ZDQtNDk2Yi1hMDE0LTljMThlZGFkNDhlYyIsInVzYWdlIjoiYWNjZXNzX3Rva2VuIiwic2NvcGUiOiJvcGVuaWQiLCJzdWIiOiIwMzc4NDE4NC00NWUxLTQyZTYtYWEyZS1iMGZkM2ZjMGRjOTIiLCJuYmYiOjE0NjE5MDEyNDcsImV4cCI6MTQ2MTkwNDg0NywiaWF0IjoxNDYxOTAxMjQ3LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDEvIn0.SNfk6EKge1nSSTWBiMLeHhuTyWePdZvztubogpnWAqgJaVvCTNgSGVJ_1-wgSe1zPi5Bu0XxwqrpSlsgKwbTPbf4v8SDFgXqUZOtz64LbVyJuQ_K0DNsD9tOMrgNR3CaMTkPAMCihknHJHomU50h_qBtrCZZCsFqBPKB3h9sQpMOPrs7Aja5OJJBVk5rrVA9uYuUs79ryILUDbphkz4UZ_x2NhYvNWrf0zmPNDqjt5k20uFXPqXIgZtJWAbWxQsPRH2PfqJranL_a57LNrbHUh1ZIKmdvTs2I3VFYpGn8ySH5oeKPfPWonGPs6bojLH8qeWf-T8Ded8LEhi-ZSoqRg


```

## Steps to reproduce: 

1. Clone git@github.com:bigfont/openiddict-core.git
1. Run `dotnet watch` in \samples\ROPC.Provider
1. Run `dotnet watch` in \samples\ROPC.ProtectedResource
1. In Fiddler, make the Provider POST
1. In Fiddler, make the Protected Resource GET, using the access_token from the response to the previous POST. 
1. In the ProtectedResource, you will *sometimes* receive the following error. It depends on the access token that you use. 

## Provider POST
```
POST http://localhost:5001/connect/token HTTP/1.1
User-Agent: Fiddler
Host: localhost:5001
Content-Type: application/x-www-form-urlencoded
Content-Length: 76

grant_type=password&scope=openid&username=test@test.com&password=Testing123!


```

## Protected Resource GET
```
GET http://localhost:5002/api/simple HTTP/1.1
Host: localhost:5002
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlExWkVESENZWVBLVUtPNl9aRzBfWTFBU09aTC05TldKLURYVVdKTkQiLCJ0eXAiOiJKV1QifQ.eyJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6IjBhYmM4NjI3LTIzZDctNDRjYy1hZWU1LTU3M2E0MTJhMzZiMiIsImp0aSI6IjNkYjc3YzY5LWYzNzUtNDNmNC1hMzVkLWRhZTY3MDcxYjExMCIsInVzYWdlIjoiYWNjZXNzX3Rva2VuIiwic2NvcGUiOiJvcGVuaWQiLCJzdWIiOiJjNjdiNmZkYS04ZmRlLTQ1NDEtYjhlYS05ZDdhMDQyZTNlZDciLCJuYmYiOjE0NjE5MDE4NTMsImV4cCI6MTQ2MTkwNTQ1MywiaWF0IjoxNDYxOTAxODUzLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDEvIn0.CWVEl46fYHWNfQZaj-ONhlse3vdbHmVEZ9a4XrtZlzZz7zsi51X7fQt0tc147VXy9-ESOL_OclmbP8SmFkdblXCEFgR1Zyp11nJ53NhPiMl5IJdIbItSSlb6Mj3hlQiQITKLS2GP9Izl5HEpxXfYYeuik2VXBsHifV4MxmLOAL5WUPa2Q6a4GnFybG3vpfH23lzjsLwYJfoWliG0qE8QW4w3hFwH7IiH5RW6200KsWJ7rTfEmd88hipbDfCpbAkjGUlm2FySdTn2rnq6UwELywtjj0reLBoE9FRhu5qPJcYFQ_DGUg8-hk79u1cNzCaG1CUej-_ZZ-4IllyCm3_gyA


```

## Error
```
fail: Microsoft.AspNetCore.Server.Kestrel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60[13]
      Connection id "0HKRFS73BL7NU": An unhandled exception was thrown by the application.
System.InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JProperty to Newtonsoft.Json.Linq.JToken.
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at AspNet.Security.OAuth.Introspection.OAuthIntrospectionHandler.<CreateTicketAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AspNet.Security.OAuth.Introspection.OAuthIntrospectionHandler.<HandleAuthenticateAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<InitializeAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

**Comment by PinpointTownes** [comment]
Thanks for reporting this bug. I marked it as critical and I'll investigate ASAP.

**Comment by PinpointTownes** [comment]
The only noticeable difference between the two tokens is the presence of a scope:

Working token:

```json
{
  "AspNet.Identity.SecurityStamp": "9e09cb59-db40-4e2d-bdcf-bcb6d9eebf0e",
  "jti": "fa0b048f-cca4-4fbf-95d8-c0f04253bb12",
  "usage": "access_token",
  "sub": "62359752-3b9a-4cec-abb4-eef05777f648",
  "nbf": 1461886137,
  "exp": 1461889737,
  "iat": 1461886137,
  "iss": "http://localhost:5000/"
}
```

Buggy token:

```json
{
  "AspNet.Identity.SecurityStamp": "79a4f1f2-09cf-4540-8b1b-5e8d1f7510e9",
  "jti": "7a0bd0ac-a9d4-496b-a014-9c18edad48ec",
  "usage": "access_token",
  "scope": "openid",
  "sub": "03784184-45e1-42e6-aa2e-b0fd3fc0dc92",
  "nbf": 1461901247,
  "exp": 1461904847,
  "iat": 1461901247,
  "iss": "http://localhost:5001/"
}
```

I suspect a bug in the way we extract/handle the scope claim from the introspection response.

**Comment by shaunluttin** [comment]
Provider POST
```
POST http://localhost:5001/connect/token HTTP/1.1
User-Agent: Fiddler
Host: localhost:5001
Content-Type: application/x-www-form-urlencoded
Content-Length: 63

grant_type=password&username=test@test.com&password=Testing123!
```

Provider Response
```
HTTP/1.1 200 OK
Cache-Control: no-cache
Date: Fri, 29 Apr 2016 04:01:20 GMT
Pragma: no-cache
Content-Length: 863
Content-Type: application/json;charset=UTF-8
Expires: -1
Server: Kestrel

{"token_type":"Bearer","access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IlExWkVESENZWVBLVUtPNl9aRzBfWTFBU09aTC05TldKLURYVVdKTkQiLCJ0eXAiOiJKV1QifQ.eyJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6IjliM2E1NmE1LTc3M2QtNDdmNi04Nzg4LTM5OWFjZGJiN2FkOCIsImp0aSI6ImE4NDFlZmQyLTcxMWQtNDExZi1hZjcxLTIwMmQ0M2JiZTkyNyIsInVzYWdlIjoiYWNjZXNzX3Rva2VuIiwic3ViIjoiNzZjMjBkMTctM2VlMi00NGE0LTkxOWYtNjUwZTgwMWI5YjI1IiwibmJmIjoxNDYxOTAyNDgwLCJleHAiOjE0NjE5MDYwODAsImlhdCI6MTQ2MTkwMjQ4MCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAxLyJ9.FbCqw9ePniXrPnTB-S5I2xkkx7Pzx_IjCskebgY4JNoDeqv_S2qkGC2PNNqVwdA5CtSIrhVZdwLZWX_u5-aaMw2gw5i43IOu5J5lBrsq3W6E94J7sW7QTQZRcotQEUfd-hs-CmTTaBGsNQMsgZLNsUXG8PUyxwOMH-jWaU0ZYn4f47iH_Nu_u9fQ5upz0RmmFKMXQc8kWzrbQGmoAK5mmSAD34ZFqC96KgwqL9IeDNJsD3FDXR5rNyeGLxx0RJEYOKEB4S5BLSdsxEmbULcWNdU732b2NrbPe7393PKJ4qvBL5V-WKyxUegVv1fN7fDf_o7-lvSFK_RCd3SwNGmj9g","expires_in":"3600"}
```

Protected Resource GET
```
GET http://localhost:5002/api/simple HTTP/1.1
Host: localhost:5002
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlExWkVESENZWVBLVUtPNl9aRzBfWTFBU09aTC05TldKLURYVVdKTkQiLCJ0eXAiOiJKV1QifQ.eyJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6IjliM2E1NmE1LTc3M2QtNDdmNi04Nzg4LTM5OWFjZGJiN2FkOCIsImp0aSI6ImE4NDFlZmQyLTcxMWQtNDExZi1hZjcxLTIwMmQ0M2JiZTkyNyIsInVzYWdlIjoiYWNjZXNzX3Rva2VuIiwic3ViIjoiNzZjMjBkMTctM2VlMi00NGE0LTkxOWYtNjUwZTgwMWI5YjI1IiwibmJmIjoxNDYxOTAyNDgwLCJleHAiOjE0NjE5MDYwODAsImlhdCI6MTQ2MTkwMjQ4MCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAxLyJ9.FbCqw9ePniXrPnTB-S5I2xkkx7Pzx_IjCskebgY4JNoDeqv_S2qkGC2PNNqVwdA5CtSIrhVZdwLZWX_u5-aaMw2gw5i43IOu5J5lBrsq3W6E94J7sW7QTQZRcotQEUfd-hs-CmTTaBGsNQMsgZLNsUXG8PUyxwOMH-jWaU0ZYn4f47iH_Nu_u9fQ5upz0RmmFKMXQc8kWzrbQGmoAK5mmSAD34ZFqC96KgwqL9IeDNJsD3FDXR5rNyeGLxx0RJEYOKEB4S5BLSdsxEmbULcWNdU732b2NrbPe7393PKJ4qvBL5V-WKyxUegVv1fN7fDf_o7-lvSFK_RCd3SwNGmj9g


```

Still an error.

**Comment by shaunluttin** [comment]
Provider POST
```
POST http://ipv4.fiddler:5001/connect/token HTTP/1.1
User-Agent: Fiddler
Host: ipv4.fiddler:5001
Content-Type: application/x-www-form-urlencoded
Content-Length: 63

grant_type=password&username=test@test.com&password=Testing123!
```

Provider Response
```
HTTP/1.1 200 OK
Cache-Control: no-cache
Date: Fri, 29 Apr 2016 04:28:03 GMT
Pragma: no-cache
Content-Length: 863
Content-Type: application/json;charset=UTF-8
Expires: -1
Server: Kestrel

{"token_type":"Bearer","access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IlExWkVESENZWVBLVUtPNl9aRzBfWTFBU09aTC05TldKLURYVVdKTkQiLCJ0eXAiOiJKV1QifQ.eyJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6IjFlZTJjMjIxLTNjZDUtNDNlMi1hMDdkLTgwMzc3MTdhMmFiYyIsImp0aSI6IjFmMTY2OWEzLTNlNDMtNGIzNC1iNjQ2LTZiNGU4MmFkYmIwNCIsInVzYWdlIjoiYWNjZXNzX3Rva2VuIiwic3ViIjoiNzdiNGI5MDEtZjEzOS00ZDA1LWI1YWEtZjEzMGMwYWMyYTc4IiwibmJmIjoxNDYxOTA0MDgzLCJleHAiOjE0NjE5MDc2ODMsImlhdCI6MTQ2MTkwNDA4MywiaXNzIjoiaHR0cDovLzEyNy4wLjAuMTo1MDAxLyJ9.JXvInr2yuL-FjPBOWxURh_kBg_qeTYlu2EUh5sjfw8r057EUbuA5GXGRRBLmHWQ8uOHJGCM8fLQuAv7vR2sXP7jxq_BSSG4W9ByOC5b8n3DOd3FodKX1PtugN_pXG8sPM_MrwRp-YaNhVjrCYOmGAxY_l3tS4XGhfNz-E3D7DSwSkF1gVxy6uxPrqyfEqnsf-tTSiqXsK3CnWPHa4hGvGY-tJSMl60S4BvE_mx4sJsGXRybU6yNfFgmGE4PGctjhQ7oN068P532gY3za0USBoyxPzn8s09DZbQLiaBDsIQJojCbAcgH7RT_lLjXpU8qyBgeLYi1XITO-DzfaAun9WA","expires_in":"3600"}
```

Protected Resource GET
```
GET http://ipv4.fiddler:5002/api/simple HTTP/1.1
Host: ipv4.fiddler:5002
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlExWkVESENZWVBLVUtPNl9aRzBfWTFBU09aTC05TldKLURYVVdKTkQiLCJ0eXAiOiJKV1QifQ.eyJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6IjFlZTJjMjIxLTNjZDUtNDNlMi1hMDdkLTgwMzc3MTdhMmFiYyIsImp0aSI6IjFmMTY2OWEzLTNlNDMtNGIzNC1iNjQ2LTZiNGU4MmFkYmIwNCIsInVzYWdlIjoiYWNjZXNzX3Rva2VuIiwic3ViIjoiNzdiNGI5MDEtZjEzOS00ZDA1LWI1YWEtZjEzMGMwYWMyYTc4IiwibmJmIjoxNDYxOTA0MDgzLCJleHAiOjE0NjE5MDc2ODMsImlhdCI6MTQ2MTkwNDA4MywiaXNzIjoiaHR0cDovLzEyNy4wLjAuMTo1MDAxLyJ9.JXvInr2yuL-FjPBOWxURh_kBg_qeTYlu2EUh5sjfw8r057EUbuA5GXGRRBLmHWQ8uOHJGCM8fLQuAv7vR2sXP7jxq_BSSG4W9ByOC5b8n3DOd3FodKX1PtugN_pXG8sPM_MrwRp-YaNhVjrCYOmGAxY_l3tS4XGhfNz-E3D7DSwSkF1gVxy6uxPrqyfEqnsf-tTSiqXsK3CnWPHa4hGvGY-tJSMl60S4BvE_mx4sJsGXRybU6yNfFgmGE4PGctjhQ7oN068P532gY3za0USBoyxPzn8s09DZbQLiaBDsIQJojCbAcgH7RT_lLjXpU8qyBgeLYi1XITO-DzfaAun9WA


```

**Comment by PinpointTownes** [comment]
The bug was caused by an incorrect handling of the `jti` claim in the introspection middleware.
It's now fixed: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/commit/fb9ffdda304eaa30e833df53fd4968774b96bc0c.

@shaunluttin thanks for reporting this nasty bug.
@MonkeyJamboree thanks for your assistance :smile:

**Comment by justicegray** [comment]
@shaunluttin, a mastodon unchained
